[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
      ]
      curvePreferences = ["CurveP521","CurveP384"]
    [tls.options.mintls13]
      minVersion = "VersionTLS13"


[http]
  [http.middlewares]
    [http.middlewares.compression.compress]
      excludedContentTypes = ["text/event-stream"]

    [http.middlewares.https-redirect.redirectScheme]
      scheme = "https"
      permanent = true

    [http.middlewares.security.headers]
      [http.middlewares.security.headers.customResponseHeaders]
        browserXssFilter = true
        contentTypeNosniff = true
        forceSTSHeader = true
        frameDeny = true
        sslRedirect = true
        #sslForceHost = true
        stsIncludeSubdomains = true
        stsPreload = true
        #ContentSecurityPolicy = "default-src 'self' 'unsafe-inline'"
        customFrameOptionsValue = "SAMEORIGIN"
        referrerPolicy = "same-origin"
        featurePolicy = "vibrate 'self'"
        stsSeconds = 315360000
        # CORS
        accessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
        accessControlAllowOriginList = ["*"]
        accessControlMaxAge = 100
        addVaryHeader = true
        # Header "x-powered-by"
        x-powered-by = "Bee.EspertaMente.com.br"
        server = "Bee.EspertaMente.com.br"

    [http.middlewares.auth.basicAuth]
      users = [
        "alcides:$apr1$GCd5TkKn$PZvSTWH7UkvkszmYSaNUI/",
      ]
      
 
  [http.routers]
    [http.routers.traefik]
      # To make traefik dashboad available over ssh
      rule = "Host(`traefik.bee.espertamente.com.br`)"
      service = "api@internal"
      middlewares = ["auth"]
        [http.routers.traefik.tls]
          certResolver = "letsencrypt"
