version: '3.7'
services:

# -----------------------------------------------------------------
# WebServer

  nginx:
    image: nginx:1.21  
    restart: unless-stopped
    container_name: nginx
    
    depends_on:
      - django_gunicorn

    ports:
      - "8080:80"

    volumes:
      # Data Storage
      - ./devops/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./django_project/static:/static

      # Define Time
      - /etc/localtime:/etc/localtime:ro

# -----------------------------------------------------------------
# Django e Gunicorn

  django_gunicorn:
    restart: unless-stopped
    container_name: django_gunicorn
    build:
      context: .
      dockerfile: ./devops/django_gunicorn/Dockerfile
 
    ports:
      - "8001:8000"

    volumes:
      # Data Storage
      - ./django_project:/app

      # Define Time
      - /etc/localtime:/etc/localtime:ro

# -----------------------------------------------------------------
# Database

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: "mysql"

    ports:
      - "33061:3306"

    volumes:
      # Configuration
      # - ./devops/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

      # Data Storage
      - ./data/mysql:/var/lib/mysql

      # Define Time
      - /etc/localtime:/etc/localtime:ro

    command:
       - --default-authentication-plugin=mysql_native_password
       - --character-set-server=utf8
       - --collation-server=utf8_general_ci

    environment:
      # Database root user passord:
      MYSQL_ROOT_PASSWORD: 'XHdfSQM1RMuitoObrigado!!!koOqc2i2kTY'
      # App Schema Access:
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'F6fmy9lMuitoObrigado!!!1SzRcD1Zqsxhs'

