version: '3.7'

networks:
  frontend:
  backend:

services:

# -----------------------------------------------------------------
# Database

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: "mysql"

    networks:
      - frontend      # It is only necessary to expose port 3306.
      - backend

    ports:
      - "3306:3306"   # Only Necessary to connect with MySQL WorkBench.

    volumes:
      # Configuration
      # - ./devops/mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

      # Data Storage
      - ./data/mysql:/var/lib/mysql

      # Define Time
      - /etc/localtime:/etc/localtime:ro

    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --disable-log-bin

    environment:
      # Database root user passord:
      MYSQL_ROOT_PASSWORD: 'NTJMbDfRZNTJMbDfRZAZV8hrcOEiPAZV8hrcOEiP'
      # App Schema Access:
      MYSQL_DATABASE: 'django_project'
      MYSQL_USER: 'django_project'
      MYSQL_PASSWORD: 'i2H9F9ukEGi2H9F9ukEGVZWNpY4lrHVZWNpY4lrH'

    labels:
      traefik.enable: false