# Generated by Django 4.0.3 on 2022-06-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_metric_objective_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
