# Generated by Django 4.0.4 on 2022-06-20 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_rename_projectname_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editproject',
            field=models.ManyToManyField(blank=True, related_name='editproject', to=settings.AUTH_USER_MODEL),
        ),
    ]
