# Generated by Django 4.0.3 on 2022-06-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
    ]
