# Generated by Django 4.0.4 on 2022-06-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='active',
        ),
    ]
