# Generated by Django 4.0.4 on 2022-06-29 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_remove_objective_project_remove_objective_userowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('can_edit_objective', models.ManyToManyField(blank=True, related_name='can_edit_objective', to=settings.AUTH_USER_MODEL)),
                ('can_read_objective', models.ManyToManyField(blank=True, related_name='can_read_objective', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_for_project', to='main.project')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
