# Generated by Django 4.0.4 on 2022-06-29 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner_metric', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='userOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner_objective', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
